---
default:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  port: 5432
development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  port: 5432
  database: keyserver_dev
  username: keyserver_dev
  password: MachSeng6Ewpihikid1
test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  port: 5432
  database: keyserver_test
  username: keyserver_dev
  password: MachSeng6Ewpihikid1
